export const ASYNC_STARTED = 'ASYNC_STARTED'
export const ASYNC_FINISHED = 'ASYNC_FINISHED'

export const PLACE_ADD_STARTED = 'PLACE_ADD_STARTED'
export const PLACE_ADD_FINISHED = 'PLACE_ADD_FINISHED'